# Generated by Django 3.0.3 on 2020-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cell',
            old_name='flagged',
            new_name='is_flagged',
        ),
        migrations.AddField(
            model_name='cell',
            name='is_uncovered',
            field=models.BooleanField(default=False),
        ),
    ]
